### ISSUE TITLE
Support env values for deplyoment

### ISSUE THREAD

**Issue by kuhnroyal** [flipt-io/helm-charts#221]
Currently it is not possible to add custom `env` variables into the deployment, only `envFrom` is supported.
I want to use it to extract DB username/password from and existing secret which is not possible with `envFrom`.

```
    env:
      - name: FLIPT_DB_USER
        valueFrom:
          secretKeyRef:
            name: flipt-cnpg-secret
            key: username
      - name: FLIPT_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: flipt-cnpg-secret
            key: password
```
